Repository woowa-techcamp-2022/web-moneybook-1, pull requests merged in 2022-07, with the labels that each got.

#6 feat: Router 구현
  client/src/router/Router.js
Labels: 프론트엔드, 구현

#14 내역 입력 폼 UI 작업
  client/src/component/InputForm/InpufForm.js
  client/src/component/InputForm/InputForm.scss
Labels: 프론트엔드, 구현, 리뷰

#15 전체 내역 UI 추가
  client/src/component/History/History.js
  client/src/component/History/History.scss
  client/src/index.scss
Labels: 프론트엔드, 구현

#18 분류, 결제수단 항목 이벤트 등록
  client/src/component/InputForm/InputForm.js
  client/src/component/InputForm/InputForm.scss
Labels: 프론트엔드, 구현

#22 History 페이지 store 연결
  client/src/component/Header/Header.js
  client/src/component/History/History.js
  client/src/component/InputForm/InputForm.js
  client/src/index.js
  client/src/store/store.js
  client/src/utils/Observable.js
  client/src/utils/date.js
  client/src/utils/generateMockData.js
Labels: 프론트엔드, 구현

#25 컴포넌트 리팩토링
  client/src/component/Header/DaySelector/DaySelector.js
  client/src/component/Header/Header.js
  client/src/component/InputForm/AmountInput/AmountInput.js
  client/src/component/InputForm/CategoryInput/CategoryInput.js
  client/src/component/InputForm/ContentInput/ContentInput.js
  client/src/component/InputForm/DateInput/DateInput.js
  client/src/component/InputForm/InputForm.js
  client/src/component/InputForm/PaymentInput/PaymentInput.js
Labels: 프론트엔드, 구현

#27 변경된 Controller, Store 적용
  client/src/component/Header/DaySelector/DaySelector.js
  client/src/component/Header/Header.js
  client/src/component/InputForm/AmountInput/AmountInput.js
  client/src/component/InputForm/CategoryInput/CategoryInput.js
  client/src/component/InputForm/ContentInput/ContentInput.js
  client/src/component/InputForm/DateInput/DateInput.js
  client/src/component/InputForm/PaymentInput/PaymentInput.js
  client/src/utils/date.js
Labels: 프론트엔드, 구현

#31 결제 수단 추가/삭제 기능
  client/src/component/CreatePaymentModal/CreatePaymentModal.js
  client/src/component/CreatePaymentModal/CreatePaymentModal.scss
  client/src/component/DeletePaymentModal/DeletePaymentModal.js
  client/src/component/DeletePaymentModal/DeletePaymentModal.scss
  client/src/component/InputForm/PaymentInput/PaymentInput.js
  client/src/controller/index.js
Labels: 프론트엔드, 구현

#34 History 컴포넌트 리팩토링
  client/src/component/History/Count/Count.js
  client/src/component/History/Filter/Filter.js
  client/src/component/History/History.js
  client/src/component/History/List/List.js
  client/src/controller/index.js
Labels: 프론트엔드, 구현, 리뷰

#39 API 예외 처리
  client/src/component/Header/Header.js
  client/src/component/InputForm/InputForm.js
  server/app.js
  server/controller/category.js
  server/controller/history.js
  server/controller/payment.js
  server/error/CustomError.js
  server/middleware/asyncErrorCatcher.js
  server/middleware/customErrorHandler.js
  server/middleware/generalErrorHandler.js
  server/middleware/sqlErrorHandler.js
  server/router/category.js
  server/router/history.js
  server/router/payment.js
  server/service/history.js
  server/service/payment.js
  server/util/constant.js
  server/util/parameterValidator.js
Labels: 백엔드, 구현, 리뷰

#48 API 요청 코드 작성
  client/src/api/category.js
  client/src/api/history.js
  client/src/api/payment.js
  client/src/component/History/List/List.js
  client/src/component/InputForm/CategoryInput/CategoryInput.js
  client/src/component/InputForm/InputForm.js
  client/src/controller/index.js
  client/src/utils/request.js
Labels: 프론트엔드, 구현

#50 History 필터링
  client/src/component/History/Count/Count.js
  client/src/component/History/Filter/Filter.js
  client/src/component/History/List/List.js
  client/src/controller/index.js
  client/src/index.js
  client/src/utils/constant.js
Labels: 프론트엔드, 구현

#51 History 페이지 버그 수정
  client/src/api/history.js
  client/src/component/Calendar/Calendar.scss
  client/src/component/Header/DaySelector/DaySelector.js
  client/src/component/History/History.scss
  client/src/component/History/List/List.js
  client/src/component/InputForm/AmountInput/AmountInput.js
  client/src/component/InputForm/CategoryInput/CategoryInput.js
  client/src/component/InputForm/DateInput/DateInput.js
  client/src/component/InputForm/InputForm.js
  client/src/index.scss
  client/src/utils/constant.js
Labels: 버그, 프론트엔드

#53 필터된 히스토리 가져오기 기능 버그
  client/src/controller/index.js
Labels: 버그, 프론트엔드

#58 필터 에러 수정
  client/src/component/History/Filter/Filter.js
Labels: 버그, 프론트엔드

#59 HistoryView 페이지 개선
  client/src/component/Calendar/Body/CalendarBody.js
  client/src/component/CreatePaymentModal/CreatePaymentModal.js
  client/src/component/DeletePaymentModal/DeletePaymentModal.js
  client/src/component/Header/Header.scss
  client/src/component/History/Filter/Filter.js
  client/src/component/History/List/List.js
  client/src/component/InputForm/AmountInput/AmountInput.js
  client/src/component/InputForm/InputForm.js
  client/src/component/InputForm/InputForm.scss
  client/src/component/InputForm/PaymentInput/PaymentInput.js
  client/src/controller/index.js
  client/src/utils/amount.js
  client/src/view/HistoryView.js
Labels: 프론트엔드, 구현

#61 도넛 차트 구현
  client/index.html
  client/src/component/Calendar/Body/CalendarBody.js
  client/src/component/Header/Header.js
  client/src/component/statistics/CategoryCost/CategoryCost.js
  client/src/component/statistics/Chart/Donut.js
  client/src/component/statistics/Statistics.js
  client/src/component/statistics/Statistics.scss
  client/src/controller/index.js
  client/src/index.js
  client/src/utils/amount.js
  client/src/utils/color.js
  client/src/utils/constant.js
  client/src/view/StatisticsView.js
  index.html
Labels: 프론트엔드, 구현, 리뷰

#74 삭제 모달 생성 시 description 전달
  client/src/component/InputForm/PaymentInput/PaymentInput.js
Labels: 버그, 프론트엔드

#75 히스토리 리스트 버그 수정
  client/src/component/InputForm/AmountInput/AmountInput.js
  client/src/component/InputForm/CategoryInput/CategoryInput.js
  client/src/component/InputForm/ContentInput/ContentInput.js
  client/src/component/InputForm/DateInput/DateInput.js
  client/src/component/InputForm/InputForm.js
  client/src/component/InputForm/PaymentInput/PaymentInput.js
Labels: 버그, 프론트엔드

#76 LoadingIndiactor 개발
  client/index.html
  client/public/image/heart.png
  client/public/image/hyeondoonge.jpeg
  client/public/image/point.png
  client/public/image/present.png
  client/public/image/sproud.png
  client/src/component/Calendar/Calendar.js
  client/src/component/History/History.js
  client/src/component/LoadingIndicator/LoadingIndicator.js
  client/src/component/LoadingIndicator/LoadingIndicator.scss
  client/src/component/statistics/Statistics.js
  client/src/index.js
  client/src/utils/constant.js
Labels: 프론트엔드, 구현

#78 프론트엔드 리팩토링
  client/src/component/Calendar/Body/CalendarBody.js
  client/src/component/Calendar/Calendar.js
  client/src/component/Calendar/Header/CalenderHeader.js
  client/src/component/Error/Error.js
  client/src/component/Header/DaySelector/DaySelector.js
  client/src/component/Header/Header.js
  client/src/component/History/Count/Count.js
  client/src/component/History/Filter/Filter.js
  client/src/component/History/History.js
  client/src/component/History/List/List.js
  client/src/component/InputForm/AmountInput/AmountInput.js
  client/src/component/InputForm/CategoryInput/CategoryInput.js
  client/src/component/InputForm/ContentInput/ContentInput.js
  client/src/component/InputForm/DateInput/DateInput.js
  client/src/component/InputForm/InputForm.js
  client/src/component/InputForm/PaymentInput/PaymentInput.js
  client/src/component/LoadingIndicator/LoadingIndicator.js
  client/src/component/Modal/Modal.js
  client/src/component/statistics/CategoryCost/CategoryCost.js
  client/src/component/statistics/Chart/Donut.js
  client/src/component/statistics/Chart/Line.js
  client/src/component/statistics/Statistics.js
  client/src/core/Chart.js
  client/src/core/Component.js
Labels: 프론트엔드, 리팩토링

#79 배포 v1.1.0
  client/index.html
  client/public/image/heart.png
  client/public/image/hyeondoonge.jpeg
  client/public/image/point.png
  client/public/image/present.png
  client/public/image/sproud.png
  client/src/api/history.js
  client/src/component/Calendar/Body/CalendarBody.js
  client/src/component/Calendar/Calendar.js
  client/src/component/Calendar/Header/CalenderHeader.js
  client/src/component/CreatePaymentModal/CreatePaymentModal.js
  client/src/component/CreatePaymentModal/CreatePaymentModal.scss
  client/src/component/DeletePaymentModal/DeletePaymentModal.js
  client/src/component/Error/Error.js
  client/src/component/Header/DaySelector/DaySelector.js
  client/src/component/Header/Header.js
  client/src/component/History/Count/Count.js
  client/src/component/History/Filter/Filter.js
  client/src/component/History/History.js
  client/src/component/History/List/List.js
  client/src/component/InputForm/AmountInput/AmountInput.js
  client/src/component/InputForm/CategoryInput/CategoryInput.js
  client/src/component/InputForm/ContentInput/ContentInput.js
  client/src/component/InputForm/DateInput/DateInput.js
  client/src/component/InputForm/InputForm.js
  client/src/component/InputForm/PaymentInput/PaymentInput.js
  client/src/component/LoadingIndicator/LoadingIndicator.js
  client/src/component/LoadingIndicator/LoadingIndicator.scss
  client/src/component/Modal/Modal.js
  client/src/component/Modal/Modal.scss
  client/src/component/statistics/CategoryCost/CategoryCost.js
  client/src/component/statistics/Chart/Donut.js
  client/src/component/statistics/Chart/Line.js
  client/src/component/statistics/Statistics.js
  client/src/component/statistics/Statistics.scss
  client/src/controller/index.js
  client/src/core/Chart.js
  client/src/core/Component.js
  client/src/index.js
  client/src/utils/constant.js
  client/src/utils/date.js
  client/src/utils/generateMockData.js
  client/src/view/HistoryView.js
  server/controller/history.js
  server/service/history.js
Labels: 배포
